server.port: 5000
app:
  domain: http://localhost:5000
  forceHttps: false
  oauth2:
    base-url: http://localhost:5100
    realm: test

security:
  oidc:
    required-authority: user-ws
    clientId: ws-pluto
    clientSecret: 00000000-0000-0000-0000-000000000000
    refresh-token-jwk-algorithm: HS256

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: false

keycloak:
  workspace-login-group: ws-users

zuul:
  routes:
    storage:
      url: http://localhost:8080
    metadata:
      url: http://localhost:8080/api/metadata/
    collections:
      url: http://localhost:8080/api/collections/
    ui:
      url: http://localhost:3000
    elasticsearch:
      url: http://localhost:9200

  include-debug-header: true
