{{- $ingress := .Values.fairspace.ingress -}}
{{- if $ingress.enabled -}}
{{- if $ingress.tls.enabled -}}
{{- if $ingress.tls.certificate.obtain -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}-fairspace
  labels:
    app: {{ template "fairspace.name" . }}
    {{- include "fairspace.labels" . | nindent 4 }}
spec:
  secretName: {{ template "fairspace.tlsSecretName" . }}
{{- with $ingress.tls.certificate.issuerRef }}
  issuerRef:
{{ toYaml . | indent 4 }}
{{- end }}
  commonName: '{{ $ingress.domain }}'
  dnsNames:
  - '{{ $ingress.domain }}'
{{- end -}}
{{- end -}}
{{- end -}}
