language: node_js

node_js:
- "node"

env:
  global:
     - APPNAME="workspace"
     - ORG="fairspace"
     - ARTIFACT_BUILD_FILE=""
     - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
     - DEPLOYMENT_CONFIG_DIR="./ci-deployment"
     - RELEASE_BRANCH="master"
     - SNAPSHOT_BRANCH="dev"
     - DOCKER_USERNAME="fairspace"
     - GITHUB_USERNAME="fairspace-ci"

# Github credentials:
# GITHUB_PASSWORD=....
     - secure: "l8Eug1n9WfHuNkrqrw0pLsxei2RsU1V+r3dty5YMDavWabBBkb5mEC9gQQ1LpPeHsLAFXxs6SXnahmZN6p9gj+yhWBnARXis7KFalMnXOyfa7PFAGmjT+rodtHy3B5CZLxcuN9wKFgDFtgrMc9xgsPN3fZEmloJKkmfGjHuGlNd0KACJFdZ16Y1pYl5AOoo0M6psyl+V1/13PSRPFxl88sOMfeyK3DbPUzF18zJ4EwQHxChJQr2oycvJl4ZhjoZ/6ivkaADySLZj0snXAbG5Rzch9lqwb/JkKbwAygXVwikCcT6YhQs5MjEbSQ1ZON0Pm2lPCH4IfP24dpraNlCn61YqGJR37WcWcGRlf+jlnjslJuJbynFlfqzzc1Blwm8DVV3hj4TfxwKSA5pba2ZHPR8TuV41pmfdLi4kOB0FZr+x8t0SdL2qHIPkCtQZ1/k/MCaTwUvS4SuURfeDI2b5Kbr7Eaoez0jdyE6jBRUhFP6Vehx22ZO5xbCsQ0pLXZdOSG8gRqHdp9b59mJgTZrx/Lycjrfy7VJzCM+n6MN4YHw8Vc5c5SHlH8XuJbUQkyjZdEFsGASHtzmq+LmZHIJ+GIbXxK9GWLXjG/3cePMXMrIuis9kHstpo1GLWHcOLVkQeZHyY8eo1iJrKKejT8LJ7/E2SzZwpZYl+9sCgKTr3e0="

     # Azure credentials
     - secure: "qikLebpdlIdCRq4fGnC/EHzjSA9ZytjDAb38+q7Zly9Dzp27iLRIa3VZhmIT2yJ13aRvps14OqceY1sfbFtt6uzkoD42wTvMNbnbv4wqWtc676SkNt/1rppj9+aRpbuUGYa+D2VmBWrLPfEaIHSxYu5mg/l6js8SgCGbLhOCuhX3ZzrfwH8U7m8fq5ROJz3RBizdnGtTB1okrA6O/cdCVdR/1WoUyu0FJDvj1wEjc7EWSSlipm/GE+rYeKg1iQxqUF1+H9K/G5gQ8xNUCr+lJIHgnx+IO7o07Pt0buDik8S4hSoe57V3QeU1oAvfbpmubz9pSW4BsDOIzITbenZx+BQUbcpGxmtx4YU2lW6jmIgSE10D35hWBbPeoaOxDm1pPtGNKp4w1j+3XExdT7/j/OSEA/EhKh59nnP8J7qmGZrs1z68q6d50Dq+m9SxFRrG0bIHMO9NKrd5J7gnva2pnixQFkXeMr3/OK1ktmamf11a66OyGN+2WylbvP8n1CTK4RCmp6GOtLw4mjck1CDN0Jqq/DSW4gLU6VcmyJkSFLOksXAcTB+KhB/Z+yBX0bEskV9VyIeXryuzVnbqE36jJ5bLZUAU/9tsyiAmHuI9hc5pz2o+fu3Dje/zYZyqB7jMsuA9vZBMyNnpo+scunS7/ZD+5IvY+7l95Blu8xbiArc="

cache:
  directories:
  - $HOME/downloads

notifications:
  hipchat:
    on_pull_requests: false
    rooms:
      - secure: "rTnDQvuOaOy65rCsCtVkUzSIV3zThn3psFfg31Tm3G4BZlqlTAYCyiSJRClXFlWDcuMJGt+/BCFJsTnsKcTphfJ+a9/UeCveax92vCiLhC7Jae0z/wHKxkCwgeKOvwe5xPLAZbrNBPjWN82AwfZE+w0XkMb7gp8rYj9Nl09rDtOa63PF3uD7L+01WUaa/ch9V2VdLuAXt9BBE4LtClZs2596B+F32KTP4g5TKFLA8y4CUcDa2ggFoeQqswAbqdrcCrWLlSWvjzTfowlCqzPKKh3ei1bhj93Dv6jNpcmJU40Co2YGGkz//kCOCM8oMIx2byP5Ter36ZRT483LWbxDiiRVDX7ii1rosq7U1GbVcZx7wt6dXRLmiMqtSEam/acnwEYmTqmCGbcnWCAx7APeXym2SX643riAjGzJQr6TwqkcxtovT3Fmm7v+o3fJXILMaR+CX/rDlfHb3U/FD3PjtzDEy+4avBVA4JPU3DIfdCPrJ3DFRfPzviTCoDsAWcNOypRHfHMJ9Dbh0N3uXHD6TnQfqUHiB7dRgpdSFAjvpGYneL+TzgY/PP4j7O/GqdY6YvUtSbBeg1r3Bw4a7tv4KCA8YvjIRwt21K64Tcz9cubmnOwytI2GZTWN2/2pXucmnABa9EBHpYO2XfQ/5FnfVf48qWrtqGeqpG9XBrrNhNM="
    template:
      - '<a href="%{build_url}">%{repository_slug}#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a> : %{author}): %{message}'
    format: html
    notify: true

before_install:
  - export KUBE_CONFIG_ENC_KEY=$encrypted_5162cfbd2a53_key
  - export KUBE_CONFIG_ENC_IV=$encrypted_5162cfbd2a53_iv
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - source ./ci/setup_env.sh

before_script:
  - 'if [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export ALLOW_SNAPSHOTS=1 DEPLOY_TARGET=ci; fi'
  - 'if [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_TARGET=demo; fi'

jobs:
  include:
    - stage: Build
      name: Helm chart
      install:
      - source ./ci/helm/install_helm.sh
      - ./ci/az/install.sh
      - ./ci/az/login.sh
      - ./ci/k8s/install_kubectl.sh
      - export PATH="$HOME/downloads/v${KUBECTL_VERSION}:$PATH"
      - ./ci/k8s/config_kubectl.sh
      script:
      - ./ci/helm/tag.sh
      - ./ci/helm/add_repos.sh
      - 'if [[ $ALLOW_SNAPSHOTS ]]; then ./ci/helm/allow_snapshot_dependencies.sh; fi'
      - ./ci/helm/build.sh
      - 'if [[ $SHOULD_RELEASE ]]; then ./ci/helm/release.sh && helm repo update; fi'
      - 'if [[ $SHOULD_RELEASE ]]; then travis_wait ./ci/helm/deploy.sh $DEPLOY_TARGET; fi'
    - # For snapshot branch, run e2e tests
      if: type != "pull_request"
      stage: e2e tests
      name: Run e2e tests
      script:
      - ./ci/run_e2e_tests.sh
    - # For release branch, update git with the new tag and update version
      if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
      stage: Versioning
      install: skip
      name: Set tag and update version
      script:
        - ./ci/helm/tag.sh
        - ./ci/versioning/add_tag_to_git.sh
        - ./ci/versioning/set_next_version.sh
