# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.demo.fairspace.app
  keycloak:
    username: keycloak
    password: keycloak-demo-123
    realm: demo
    clientSecret: db67da94-fa31-47cd-8c42-0ed295790841

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.demo.fairspace.app
    tls:
      certificate:
        dns01Provider: azuredns-demo

# Specific settings for Pluto subchart
pluto:
  keycloak:
    baseUrl: https://keycloak.hyperspace.demo.fairspace.app
    realm: demo
  tracing:
    enabled: false
  services:
    jupyter: https://jupyterhub.workspace.demo.fairspace.app

# Specific settings for Titan subchart
titan:
  auth:
    tokenUrl: https://keycloak.hyperspace.demo.fairspace.app/auth/realms/demo/protocol/openid-connect/token
    clientId: workspace-demo-pluto
  tracing:
    enabled: false
  collections:
    permissionsUrl: https://workspace.demo.fairspace.app/api/collections/permissions?location=%s

# Specific settings for Ceres subchart
ceres:
  app:
    oauth2:
      baseUrl: https://keycloak.hyperspace.demo.fairspace.app
      realm: demo
    tracing:
      enabled: false

# Specific settings for Neptune subchart
neptune:
  app:
    oauth2:
      baseUrl: https://keycloak.hyperspace.demo.fairspace.app
      realm: demo
    tracing:
      enabled: false
    metadata:
      baseUrl: https://workspace.demo.fairspace.app


# Specific settings for JupyterHub subchart
jupyterhub:
  rbac:
    enabled: false
  auth:
    custom:
      config:
        client_id: workspace-demo-pluto
        client_secret: db67da94-fa31-47cd-8c42-0ed295790841
        openid_url: https://keycloak.hyperspace.demo.fairspace.app/auth/realms/demo/protocol/openid-connect/
        session_url: https://workspace.demo.fairspace.app/account/tokens
  singleuser:
    extraEnv:
      WORKSPACE_URL: https://workspace.demo.fairspace.app
  hub:
    extraEnv:
      JUPYTERHUB_CRYPT_KEY: 8232144c8cba2105c71ee2f0e28158f2cc4417bfd103764017422393619208fe
  proxy:
    secretToken: "a09ebe4bd113e5bded426a1335e3f61f53850a395705563b20115bf717a11c93"
