views:
  - name: Study
    title: Studies
    itemName: Study
    types:
      - https://fairspace.nl/pfizer#Study
    columns:
      - name: title
        title: Title
        source: http://purl.org/dc/terms/title
        type: text
        displayIndex: 1
      - name: treatmentId
        title: Treatment identifier
        source: https://fairspace.nl/pfizer#hasTreatmentId
        rdfType: https://fairspace.nl/pfizer#TreatmentId
        type: termSet
        displayIndex: 7
      - name: treatmentName
        title: Treatment name
        source: https://fairspace.nl/pfizer#hasTreatmentName
        type: Set
        displayIndex: 8
      - name: clinicalStudyPhase
        title: Clinical study phase
        source: https://fairspace.nl/pfizer#hasClinicalStudyPhase
        rdfType: https://fairspace.nl/pfizer#ClinicalStudyPhase
        type: term
        displayIndex: 2
      - name: primaryEndpoint
        title: Primary endpoint
        source: https://fairspace.nl/pfizer#hasPrimaryEndpoint
        type: text
        displayIndex: 14
      - name: cunductedInMultipleSites
        title: Conducted in multiple sites
        source: https://fairspace.nl/pfizer#conductedInMultipleSites
        type: boolean
        displayIndex: 22
      - name: plannedNumberOfSubjects
        title: Planned number of subjects
        source: https://fairspace.nl/pfizer#hasPlannedNumberOfSubjects
        type: number
        displayIndex: 9
      - name: actualTotalNumberOfSubjects
        title: Actual total number of subjects
        source: https://fairspace.nl/pfizer#hasActualNumberOfSubjects
        type: number
        displayIndex: 10
      - name: therapeuticArea
        title: Therapeutic area
        source: https://fairspace.nl/pfizer#hasTherapeuticArea
        rdfType: https://fairspace.nl/pfizer#TherapeuticArea
        type: termSet
        displayIndex: 16
      - name: indicationVerbatimTerm
        title: Indication verbatim term
        source: https://fairspace.nl/pfizer#hasIndicationVerbatimTerm
        rdfType: https://fairspace.nl/pfizer#IndicationVerbatimTerm
        type: termSet
        displayIndex: 11
      - name: indicationPreferredTerm
        title: Indication preferred term
        source: https://fairspace.nl/pfizer#hasIndicationPreferredTerm
        rdfType: https://fairspace.nl/pfizer#IndicationPreferredTerm
        type: termSet
        displayIndex: 12
      - name: drugsMechanismOfAction
        title: Drug's mechanism of action
        source: https://fairspace.nl/pfizer#hasDrugsMechanismOfAction
        rdfType: https://fairspace.nl/pfizer#CompoundMechanismOfAction
        type: termSet
        displayIndex: 13
      - name: sponsoringUnit
        title: Sponsoring unit
        source: https://fairspace.nl/pfizer#hasSponsoringUnit
        rdfType: https://fairspace.nl/pfizer#SponsoringUnit
        type: termSet
        displayIndex: 17
      - name: contractResearchOrganization
        title: Contract research organization
        source: https://fairspace.nl/pfizer#hasContractResearchOrganization
        rdfType: https://fairspace.nl/pfizer#ContractResearchOrganization
        type: termSet
      - name: countriesInvolved
        title: Countries involved
        source: https://fairspace.nl/pfizer#hasCountryInvolved
        rdfType: https://fairspace.nl/pfizer#Country
        type: termSet
        displayIndex: 24
      - name: studyStartDate
        title: Study start date
        source: https://fairspace.nl/pfizer#hasStudyStartDate
        type: date
        displayIndex: 3
      - name: studyStatus
        title: Study status
        source: https://fairspace.nl/pfizer#hasStudyStatus
        rdfType: https://fairspace.nl/pfizer#StudyStatus
        type: term
        displayIndex: 4
      - name: studyDuration
        title: Study duration (months)
        source: https://fairspace.nl/pfizer#hasDuration
        type: number
        displayIndex: 5
      - name: clinicalStudyReportDate
        title: Clinical study report date
        source: https://fairspace.nl/pfizer#hasClinicalStudyReportDate
        type: date
        displayIndex: 6
      - name: clinicalStudyTeamLead
        title: Clinical study team lead
        source: https://fairspace.nl/pfizer#hasClinicalStudyTeamLead
        type: Set
        displayIndex: 18
      - name: clinicalDataScientist
        title: Clinical data scientist
        source: https://fairspace.nl/pfizer#hasClinicalDataScientist
        type: Set
        displayIndex: 19
      - name: leadClinician
        title: Lead clinician
        source: https://fairspace.nl/pfizer#hasLeadClinician
        type: Set
        displayIndex: 20
      - name: demographicInformationAvailable
        title: Demographic information available
        source: https://fairspace.nl/pfizer#demographicInformationAvailable
        type: boolean
        displayIndex: 21
      - name: medicalHistoryAvailable
        title: Medical history available
        source: https://fairspace.nl/pfizer#medicalHistoryAvailable
        type: boolean
    join:
      - view: DataFile
        on: https://fairspace.nl/pfizer#relatedToStudy
        reverse: true
        include:
          - imagingModality
  - name: DataFile
    title: Data files
    itemName: Data File
    types:
      - https://fairspace.nl/pfizer#DataFile
    columns:
      - name: fileType
        title: File type
        source: https://fairspace.nl/pfizer#hasFileType
        rdfType: https://fairspace.nl/pfizer#FileType
        type: term
        displayIndex: -6
      - name: imagingModality
        title: Imaging modality
        source: https://fairspace.nl/pfizer#hasImagingModality
        rdfType: https://fairspace.nl/pfizer#ImagingModality
        type: termSet
        displayIndex: -5
      - name: acquisitionDate
        title: Acquisition date
        source: https://fairspace.nl/pfizer#hasAcquisitionDate
        type: date
        displayIndex: -4
      - name: visit
        title: Visit
        source: https://fairspace.nl/pfizer#acquiredAtVisit
        type: Set
        displayIndex: -3
      - name: visitDescription
        title: Visit description
        source: https://fairspace.nl/pfizer#hasVisitDescription
        type: Set
        displayIndex: -2
    join:
      - view: Study
        on: https://fairspace.nl/pfizer#relatedToStudy
        reverse: false
        displayIndex: -7
        include:
          - id
