# External dependencies for running Fairspace
external:
  keycloak:
    baseUrl: http://keycloak.local
    realm: fairspace
    clientId: workspace-client
    clientSecret: '**********'

# Settings for Fairspace
fairspace:
  name: "Local Fairspace"
  description: "Local Fairspace"
  ingress:
    domain: fairspace.local
    tls:
      enabled: false
  features:
    - ExtraStorage
  icons:
    test-icon: test.svg
    jupyter: /icons/jupyter.svg
    omics: /icons/omics.svg
    metadata: /icons/metadata.svg
  services:
    JupyterHub:
      name: "JupyterHub"
      url: http://jupyterhub.local/user/${username}/lab
      icon-name: jupyter
  metadata-sources:
    internal:
      label: "Metadata"
      icon-name: metadata
    test:
      name: test
      label: "External Metadata"
      url: http://fairspace.local/api/
      icon-name: "test-icon"

# Specific settings for Saturn subchart
saturn:
  # loglevel: debug
  image:
    image: saturn-local
    tag: latest
    pullPolicy: Never
  persistence:
    extra-file-storage:
      size: 5Gi

# Specific settings for Pluto subchart
pluto:
  # logLevel: debug
  image:
    image: pluto-local
    tag: latest
    pullPolicy: Never
  responseTimeoutMillis: 600000  # 10 minutes
  connectTimeoutMillis: 2000
  maxFileSize: 1GB
