# External dependencies for running the workspace
external:
  keycloak:
    baseUrl: https://keycloak.ci.fairway.app
    username: keycloak
    password: keycloak-ci-123
    realm: ci
    clientId: workspace-ci-pluto
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510
  elasticsearch:
    enabled: true
    transport:
      host: workspace-ci-elasticsearch-discovery.workspace-ci.svc.cluster.local
    rest:
      host: workspace-ci-elasticsearch-client.workspace-ci.svc.cluster.local

# Set passwords to prevent having a new password at every upgrade
keycloak:
  keycloak:
    password: keycloak-ci-123
    persistence:
      dbPassword: "9FGwLKpEu$4w/knG"

# Settings for the workspace
workspace:
  name: "CI Workspace"
  description: "CI Workspace"
  ingress:
    domain: workspace.ci.fairway.app
  enableExperimentalFeatures: false
  configurationScripts:
    keycloak:
      pullPolicy: Always
  testuser:
    generate: true
    password: fairspace123

services:
  jupyterhub: https://jupyter.workspace.ci.fairway.app


# Specific settings for Saturn subchart
saturn:
  nodes:
    - name: node1
      persistence:
        files:
          size: 60Gi
          storageClass: expandable
        database:
          size: 60Gi
          storageClass: expandable
      resources:
        limits:
          cpu: 1
          memory: 16Gi
        requests:
          cpu: 500m
          memory: 512Mi
    - name: node2
      persistence:
        files:
          size: 60Gi
          storageClass: expandable
        database:
          size: 60Gi
          storageClass: expandable
      resources:
        limits:
          cpu: 1
          memory: 16Gi
        requests:
          cpu: 500m
          memory: 512Mi
  image:
    pullPolicy: Always
  customStorageClass:
      create: true
      name: expandable
      type: pd-standard
      provisioner: kubernetes.io/gce-pd
      allowVolumeExpansion: true
  mail:
    mail.from: pavel@thehyve.nl
    mail.user: AKIAISXHGXUIMMU75YVA
    mail.password: Avjpey3XBSvnlPfWGTS2qEjiJykvbDJtj6zWW3fCZILl
    mail.transport.protocol: smtp
    mail.smtp.auth: true
    mail.smtp.host: email-smtp.us-east-1.amazonaws.com
    mail.smtp.port: 587
    mail.smtp.starttls.enable: true


# Specific settings for Mercury subchart
mercury:
  image:
    pullPolicy: Always
# Specific settings for Mercury subchart
docs:
  image:
    pullPolicy: Always
