# External dependencies for running the fairspace
external:
  keycloak:
    baseUrl: https://keycloak.ci.fairway.app
    realm: ci
    clientId: fairspace-ci-private
    clientSecret: 1877ac71-15ad-4245-bea8-d57c9cbaf3ce

# Settings for fairspace
fairspace:
  name: "Test Fairspace"
  description: "Test Fairspace"
  ingress:
    domain: fairspace.test.fairway.app
  features: []
  services:
    JupyterHub: https://jupyter.fairspace.ci.fairway.app/user/${username}/lab

# Specific settings for Saturn subchart
saturn:
  persistence:
    files:
      size: 60Gi
      storageClass: expandable
    database:
      size: 60Gi
      storageClass: expandable
    audit:
      size: 10Gi
      storageClass: expandable
  resources:
    limits:
      cpu: 1
      memory: 16Gi
    requests:
      cpu: 500m
      memory: 512Mi
  customStorageClass:
      create: true
      name: expandable
      type: pd-standard
      provisioner: kubernetes.io/gce-pd
      allowVolumeExpansion: true

pluto:
  socketTimeoutMillis: 10000
  connectTimeoutMillis: 2000
  maxFileSize: 1GB
  maxRequestSize: 1GB
  externalDomains:
    - https://fairspace.ci.fairway.app
  backends:
    storageRoutes:

postgres:
  persistence:
    storage:
      size : 60Gi