kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.external.keycloak.realm }}-organisationadmin
type: Opaque
data:
{{- if .Values.workspace.organisationadmin.username }}
  username: {{ .Values.workspace.organisationadmin.username | b64enc | quote }}
{{- else }}
  username: {{ printf "organisation-admin-%s" .Values.workspace.name | b64enc | quote }}
{{- end }}
{{- if .Values.workspace.organisationadmin.password }}
  password: {{ .Values.workspace.organisationadmin.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
