kind: Secret
apiVersion: v1
metadata:
  name: {{ template "hyperspace.keycloak.realm" . }}-orgnisation-admin
type: Opaque
data:
{{- if .Values.hyperspace.organisationadmin.username }}
  username: {{ .Values.hyperspace.organisationadmin.username | b64enc | quote }}
{{- else }}
  username: {{ printf "orgnisation-admin-%s" (include "hyperspace.keycloak.realm" .) | b64enc | quote }}
{{- end }}
{{- if .Values.hyperspace.organisationadmin.password }}
  password: {{ .Values.hyperspace.organisationadmin.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
