pluto:
  oauth2:
    base-url: http://localhost:5100
    backend-url: ${KEYCLOAK_BACKEND_URL:${pluto.oauth2.base-url}}
    realm: fairspace
  max-file-size: 2GB
server:
  error:
    whitelabel:
      enabled: false
  max-http-header-size: 65535


spring:
  application:
    name: Pluto
  main:
    web-application-type: reactive
  sleuth:
    sampler:
      probability: 1.0
  web:
    resources:
      static-locations: classpath:static,file:/opt/mercury
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
      default-filters:
      - RemoveRequestHeader=Pragma X-Frame-Options X-Content-Type-Options X-XSS-Protection X-Permitted-Cross-Domain-Policies Origin
        # Including the ORIGIN header would trigger CORS filtering downstream, but Pluto is already doing the filtering.
      httpclient:
        connect-timeout: 2000
        response-timeout: 600s

management:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

logging:
  level:
    root: INFO

security:
  oidc:
    auth-url: ${pluto.oauth2.base-url}/realms/${pluto.oauth2.realm}/protocol/openid-connect/auth
    logout-url: ${pluto.oauth2.base-url}/realms/${pluto.oauth2.realm}/protocol/openid-connect/logout?post_logout_redirect_uri=%s&id_token_hint=%s
    token-url: ${pluto.oauth2.backend-url}/realms/${pluto.oauth2.realm}/protocol/openid-connect/token
    jwk-key-set-url: ${pluto.oauth2.backend-url}/realms/${pluto.oauth2.realm}/protocol/openid-connect/certs
    redirect-after-logout-url: ${pluto.oauth2.base-url}
    clientId: workspace-client
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}
    scope: openid

  # Specify urls for security configuration.
  # URLs with permitAll do not require any authentication
  # URLs with needAuthentication are allowed to be accessed by any user. They are needed
  #      to show an error message if the user is not allowed to access the workspace
  # URLs with needAuthorization need an authorized user.
  urls:
    permitAll:
    - /actuator/health
    - /actuator/health/*
    - /error
    - /manifest.json
    - /login
    - /logout
    - /authorize
    - /favicon.ico
    needsAuthorization:
    - /*
