server.port: 8080

pluto:
  domains:
    - http://localhost:8080
  force-https: false
  downstreamServiceHealthUrl: http://localhost:8090/api/health/
  oauth2:
    base-url: http://localhost:5100
    realm: fairspace
  storages:
    test:
       name: test
       label: Test
       url: http://localhost:8090/api/webdav
       search-url: http://localhost:8090/api/search/files
       root-directory-iri: http://localhost:8080/api/webdav

spring:
  cloud:
    gateway:
      routes:
      - id: storage-test-webdav
        uri: ${pluto.storages.test.url}
        predicates:
        - Path=/api/storages/test/webdav/**
        filters:
        - RewritePath=/api/storages/test/webdav/(?<segment>.*), /api/webdav/$\{segment}
      - id: storage-test-search
        uri: ${pluto.storages.test.search-url}
        predicates:
        - Path=/api/storages/test/search/files
        filters:
        - RewritePath=/api/storages/test/search/files, /api/search/files
      - id: saturn-post-request-size
        uri: http://localhost:8090/api/
        predicates:
        - Method=POST
        - Path=/api/**
        filters:
        - name: RequestSize
          args:
            maxSize: ${pluto.max-file-size}
      - id: saturn
        uri: http://localhost:8090/
        predicates:
        - Path=/api/**
