{{- $global := . }}
{{- range .Values.saturn.nodes }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $global.Release.Name }}-saturn-{{.name}}-database
  labels:
    app: saturn
    chart: {{- printf "%s-%s" $global.Chart.Name $global.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
    release: {{ $global.Release.Name }}
    heritage: {{ $global.Release.Service }}
{{- if $global.Values.saturn.persistence.database.annotations }}
  annotations:
{{ toYaml $global.Values.saturn.persistence.database.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{- if .persistence.database.size }}
      storage: {{ .persistence.database.size | quote }}
      {{- else }}
      storage: {{ $global.Values.saturn.persistence.database.size | quote }}
      {{- end }}
  {{- if .persistence.database.storageClass }}
  {{- if (eq "-" .persistence.database.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .persistence.database.storageClass | quote }}
  {{- end }}
  {{- else if $global.Values.saturn.persistence.database.storageClass }}
  {{- if (eq "-" $global.Values.saturn.persistence.database.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ $global.Values.saturn.persistence.database.storageClass }}"
  {{- end }}
  {{- end }}
{{- end}}
