apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name }}-pluto
  labels:
    app: pluto
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{.Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: pluto
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: pluto
        release: {{ .Release.Name }}
{{- if .Values.podAnnotations.pluto }}
      annotations:
{{ toYaml .Values.podAnnotations.pluto | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Release.Name }}-pluto
        image: "{{ .Values.pluto.image.image }}:{{ .Values.pluto.image.tag }}"
        imagePullPolicy: {{ .Values.pluto.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-oauth-client"
                key: clientSecret
        volumeMounts:
        - name: config-volume
          mountPath: /opt/config
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: {{ .Values.pluto.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.pluto.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.pluto.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.pluto.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path:  /actuator/health
            port: 8080
          periodSeconds: {{ .Values.pluto.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.pluto.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.pluto.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.pluto.resources | indent 12 }}
  {{- with .Values.pluto.nodeSelector }}
nodeSelector:
{{ toYaml . | indent 8 }}
  {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-pluto
      terminationGracePeriodSeconds: {{ .Values.pluto.terminationGracePeriodSeconds }}
