apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pluto
  labels:
    app: pluto
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pluto
    release: {{ .Release.Name }}
