# Application's port
port: 8080
jena:
  # Base IRI for all metadata entities
  metadataBaseIRI: "http://localhost/iri/"
  # Base IRI for all vocabulary entities
  vocabularyBaseIRI: "http://localhost/vocabulary/"
  # Jena's TDB2 database path
  datasetPath: "data/db"
  # Path of the transaction log
  transactionLogPath: "data/log"
  elasticSearch:
    # Enables ElasticSearch integration
    enabled: true
    # Makes availability of ElasticSearch mandatory
    required: false
    settings:
      # Map of hosts and ports. The host could also be an IP Address
      hostToPortMapping:
        "127.0.0.1": 9300
      # Name of the Cluster. Defaults to "elasticsearch". Set to "docker-cluster" for a dockerized ES setup.
      clusterName: "docker-cluster"
      # Number of shards. Defaults to 1
      shards: 1
      # Number of replicas. Defaults to 1
      replicas: 1
      # Name of the index. Defaults to "fairspace"
      indexName: "fairspace"
auth:
  # Enables JWT/JWKS authentication. Defaults to false.
  enabled: false
  # User roles (for local development only)
  developerRoles:
    - datasteward
  # JWKS URL
  jwksUrl: "https://keycloak.hyperspace.ci.fairway.app/auth/realms/ci/protocol/openid-connect/certs"
  # JWK encryption algorithm. Defaults to "RS256"
  jwtAlgorithm: "RS256"
  # Role name for data stewards, who are allowed to modify the vocabulary
  dataStewardRole: "datasteward"
webDAV:
  # Path of the WebDAV's local blob store
  blobStorePath: "data/blobs"
mail:
  mail.from: info@fairspace.com
  mail.user: user
  mail.password: password
  mail.transport.protocol: smtp
  mail.smtp.auth: true
  mail.smtp.host: host
  mail.smtp.port: 587
  mail.smtp.starttls.enable: true
