views:
  - name: S1Objects
    title: S001
    itemName: S001
    types:
      - https://fairspace.nl/ontology#s001
    columns:
      - name: descriptionA001
        title: Description 001
        source: https://fairspace.nl/ontology#a001
        type: text
    join:
        - view: S2Objects
          on: https://fairspace.nl/ontology#hasParent
          reverse: true
          include:
            - id
  - name: S2Objects
    title: S002
    itemName: s002
    types:
      - https://fairspace.nl/ontology#s002
    columns:
      - name: descriptionA002
        title: Description 002
        source: https://fairspace.nl/ontology#a002
        type: text
        displayIndex: -1
    join:
    - view: S1Objects
      on: https://fairspace.nl/ontology#hasParent
      include:
        - id
    - view: S3Objects
      on: https://fairspace.nl/ontology#hasParent
      reverse: true
      displayIndex: -2
      include:
        - id
  - name: S3Objects
    title: S003
    itemName: s003
    types:
      - https://fairspace.nl/ontology#s003
    columns:
      - name: descriptionA003
        title: Description 003
        source: https://fairspace.nl/ontology#a003
        type: text
        displayIndex: 3
      - name: numberAttribute
        title: Count
        source: https://fairspace.nl/ontology#a005
        type: number
        displayIndex: 2
    join:
    - view: S2Objects
      on: https://fairspace.nl/ontology#hasParent
      include:
        - id
    - view: S4Objects
      on: https://fairspace.nl/ontology#hasParent
      reverse: true
      include:
        - id
  - name: S4Objects
    title: S004
    itemName: s004
    types:
      - https://fairspace.nl/ontology#s004
    columns:
      - name: descriptionA004
        title: Description 004
        source: https://fairspace.nl/ontology#a004
        type: text
        displayIndex: 1
      - name: treatmentType
        title: Treatment Type
        source: https://fairspace.nl/ontology#hasTreatmentType
        rdfType: https://fairspace.nl/ontology#treatmentType
        type: termSet
        displayIndex: -1
    join:
    - view: S3Objects
      on: https://fairspace.nl/ontology#hasParent
      displayIndex: 2
      include:
        - id
