views:
  - name: Study
    title: Studies
    itemName: Study
    types:
      - https://www.fns-cloud.eu/study
    columns:
      - name: name
        title: Name
        source: http://purl.org/dc/terms/title
        type: text
      - name: studyType
        title: Study Type
        source: https://www.fns-cloud.eu/has_study_type
        rdfType: https://www.fns-cloud.eu/study_type
        type: term
      - name: treatmentType
        title: Treatment Type
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasTreatmentType
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#treatmentType
        type: termSet
      - name: sampleType
        title: Sample Type
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasSampleType
        type: termSet
      - name: subjectCount
        title: Subject Count
        source: https://fns-cloud.eu/ontology/dbnp-data-model#subjectCount
        type: number
      - name: identifier
        title: Identifier
        source: http://purl.org/dc/terms/identifier
        type: text
    join:
      - view: Subject
        on: https://fns-cloud.eu/ontology/dbnp-data-model#isSubjectPartOfStudy
        reverse: true
        include:
          - id
      - view: Sample
        on: https://fns-cloud.eu/ontology/dbnp-data-model#isSamplePartOfStudy
        reverse: true
        include:
          - id
      - view: Resource
        on: https://fns-cloud.eu/ontology/dbnp-data-model#aboutStudy
        reverse: true
        include:
          - id
  - name: Subject
    title: Subjects
    itemName: Subject
    types:
      - https://fns-cloud.eu/ontology/dbnp-data-model#Subject
    columns:
      - name: gender
        title: Gender
        source: https://fns-cloud.eu/ontology/dbnp-data-model#isOfGender
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#Gender
        type: term
        priority: 1000
      - name: species
        title: (Host) species
        source: https://fns-cloud.eu/ontology/dbnp-data-model#isOfSpecies
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#Species
        type: term
      - name: age
        title: Age
        source: https://fns-cloud.eu/ontology/dbnp-data-model#age
        type: number
      - name: bmi
        title: Body-mass index
        source: https://www.fns-cloud.eu/FNS-H_0000000095
        type: number
      - name: height
        title: Height (m)
        source: https://fns-cloud.eu/ontology/dbnp-data-model#height
        type: number
      - name: description
        title: Description
        source: http://purl.org/dc/terms/description
        type: text
    join:
      - view: Study
        on: https://fns-cloud.eu/ontology/dbnp-data-model#isSubjectPartOfStudy
        include:
          - id
      - view: Sample
        on: https://fns-cloud.eu/ontology/dbnp-data-model#belongsToSubject
        reverse: true
        include:
          - id
      - view: Resource
        on: https://fns-cloud.eu/ontology/dbnp-data-model#aboutSubject
        reverse: true
        include:
          - id
  - name: Sample
    title: Samples
    itemName: Sample
    types:
      - https://fns-cloud.eu/ontology/dbnp-data-model#Sample
    columns:
      - name: biosampleId
        title: Biosample id
        source: https://fns-cloud.eu/ontology/dbnp-data-model#bioSampleId
        type: text
      - name: analysisFile
        title: Analyses files
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasAnalysisFile
        type: text
      - name: species
        title: (Host) species
        source: https://fns-cloud.eu/ontology/dbnp-data-model#isOfSpecies
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#Species
        type: term
      - name: investigationType
        title: Investigation type
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasInvestigationType
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#investigationType
        type: term
      - name: environmentBiome
        title: Environment biome
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasEnvironmentBiome
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#environmentBiome
        type: term
      - name: environmentFeature
        title: Environment feature
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasEnvironmentFeature
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#environmentFeature
        type: term
      - name: locationLatitude
        title: Location lat.
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasLocationLatitude
        type: number
      - name: locationLongitude
        title: Location long.
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasLocationLongitude
        type: number
      - name: sequencingMethod
        title: Sequencing method
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasSequencingMethod
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#sequencingMethod
        type: term
      - name: hostDiet
        title: Host diet
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasHostDiet
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#diet
        type: term
      - name: specialDiet
        title: Special diet
        source: https://fns-cloud.eu/ontology/dbnp-data-model#hasSpecialDiet
        rdfType: https://fns-cloud.eu/ontology/dbnp-data-model#diet
        type: term
    join:
      - view: Subject
        on: https://fns-cloud.eu/ontology/dbnp-data-model#belongsToSubject
        include:
          - id
      - view: Study
        on: https://fns-cloud.eu/ontology/dbnp-data-model#isSamplePartOfStudy
        include:
          - id
      - view: Resource
        on: https://fns-cloud.eu/ontology/dbnp-data-model#aboutSample
        reverse: true
        include:
          - id
  - name: Resource
    title: Collections and files
    itemName: Name
    types:
      - https://fairspace.nl/ontology#Collection
      - https://fairspace.nl/ontology#Directory
      - https://fairspace.nl/ontology#File
    columns:
      - name: description
        title: Description
        source: http://www.w3.org/2000/01/rdf-schema#comment
        type: text
      - name: type
        title: Resource type
        source: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
        type: term
      - name: dateCreated
        title: File created
        source: https://fairspace.nl/ontology#dateCreated
        type: date
      - name: keywords
        title: Key words
        source: http://www.w3.org/ns/dcat#keyword
        type: set
    join:
      - view: Study
        on: https://fns-cloud.eu/ontology/dbnp-data-model#aboutStudy
        include:
          - id
      - view: Subject
        on: https://fns-cloud.eu/ontology/dbnp-data-model#aboutSubject
        include:
          - id
      - view: Sample
        on: https://fns-cloud.eu/ontology/dbnp-data-model#aboutSample
        include:
          - id
