version: '3'

services:
  fairspace-keycloak-postgres:
    image: postgres:11-alpine
    container_name: fairspace-keycloak-database
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - fairspace-keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - fairspace-keycloak-db-network
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-keycloak-postgres

  fairspace-keycloak:
    image: keycloak/keycloak:20.0.3
    container_name: fairspace-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://fairspace-keycloak-postgres/keycloak?user=keycloak&password=keycloak
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:?Please configure KEYCLOAK_HOSTNAME.}
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_STORAGE_AREA_CLIENT: ${WORKSPACE_CLIENT_ID:?Please configure WORKSPACE_CLIENT_ID}
      PROXY_ADDRESS_FORWARDING: 'true'
      WORKSPACE_URL: ${WORKSPACE_URL:?Please configure WORKSPACE_URL.}
      WORKSPACE_DEBUG_URL: ${WORKSPACE_DEBUG_URL:?Please configure WORKSPACE_DEBUG_URL.}
      KC_HEALTH_ENABLED: true
    ports:
      - ${KEYCLOAK_PORT:-5100}:8080
    depends_on:
      - fairspace-keycloak-postgres
    networks:
      - fairspace-keycloak-db-network
    volumes:
      - ./keycloak/setup-realm.sh:/opt/jboss/startup-scripts/setup-realm.sh
      # - ./keycloak/realm-template.json:/tmp/realm-template.json
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-keycloak
    command: 
      - start-dev 
      - --import-realm 

  fairspace-postgres:
    image: postgres:13-alpine
    container_name: fairspace-postgresql
    environment:
      POSTGRES_DB: fairspace
      POSTGRES_USER: fairspace
      POSTGRES_PASSWORD: fairspace
    ports:
      - ${POSTGRESQL_PORT:-9432}:5432
    volumes:
      - fairspace-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-postgres

volumes:
  fairspace-keycloak-postgres-data:
  fairspace-postgres-data:

networks:
  fairspace-keycloak-db-network:
    driver: bridge
