services:
  fairspace-keycloak-postgres:
    image: postgres:15-alpine
    container_name: fairspace-keycloak-database
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - fairspace-keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - fairspace-keycloak-db-network
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-keycloak-postgres

  fairspace-keycloak:
    image: keycloak/keycloak:20.0.3
    container_name: fairspace-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://fairspace-keycloak-postgres/keycloak?user=keycloak&password=keycloak
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:?Please configure KEYCLOAK_HOSTNAME.}
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      PROXY_ADDRESS_FORWARDING: 'true'
      WORKSPACE_URL: ${WORKSPACE_URL:?Please configure WORKSPACE_URL.}
      WORKSPACE_DEBUG_URL: ${WORKSPACE_DEBUG_URL:?Please configure WORKSPACE_DEBUG_URL.}
      WORKSPACE_CLIENT_ID: ${WORKSPACE_CLIENT_ID:?Please configure WORKSPACE_CLIENT_ID}
      KC_HEALTH_ENABLED: 'true'
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:?Please configure KEYCLOAK_REALM}
    ports:
      - ${KEYCLOAK_PORT:-5100}:8080
    depends_on:
      - fairspace-keycloak-postgres
    networks:
      - fairspace-keycloak-db-network
    volumes:
      - ./keycloak/realm-template.json:/opt/keycloak/data/import/realm-template.json
    restart: unless-stopped
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-keycloak
    command:
      - start-dev
      - --import-realm

  fairspace-postgres:
    image: postgres:15-alpine
    container_name: fairspace-postgresql
    environment:
      POSTGRES_DB: fairspace
      POSTGRES_USER: fairspace
      POSTGRES_PASSWORD: fairspace
    ports:
      - ${POSTGRESQL_PORT:-9432}:5432
    volumes:
      - fairspace-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c", "checkpoint_timeout=43200"]
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-postgres

  clickhouse:
    image: clickhouse/clickhouse-server:22.6
    container_name: fairspace-clickhouse
    restart: unless-stopped
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=fairspace
      - CLICKHOUSE_USER=fairspace
      - CLICKHOUSE_PASSWORD=fairspace
    volumes:
      - ./clickhouse/data/:/data/
      - ./clickhouse/scripts/:/docker-entrypoint-initdb.d/
#      - fairspace-clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    logging:
      driver: ${DOCKER_LOGGING_DRIVER:-journald}
      options:
        labels: application
        tag: fairspace-clickhouse
    ports:
      - 8123:8123

volumes:
  fairspace-keycloak-postgres-data:
  fairspace-postgres-data:
  fairspace-clickhouse-data:

networks:
  fairspace-keycloak-db-network:
    driver: bridge
