# This workflow is triggered on any PR's changes

name: PR - Build Fairspace

on:
  pull_request:

jobs:
  generate-version: # to have one common unique version for all built artifacts
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.version.outputs.snapshot_version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - id: version
        name: Generating version tag for artifacts
        run: |
          # EXTRACT VERSION
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "Building images from the branch: $BRANCH"
          VER=$(cat ./VERSION)
          echo "Building images for version: $VER"     

          # GET DATE AND TIME FOR VERSIONING 
          DATE=$(date "+%Y%m%d%H%M%S")

          # DOCKER TAG TO BE ATTACHED (SHARED WITHIN OUTPUT):
          SNAPSHOT_VERSION=SNAPSHOT-$VER-$DATE
          echo "snapshot_version=$SNAPSHOT_VERSION" >> "$GITHUB_OUTPUT"
          echo "Docker tag to be attached to images: $SNAPSHOT_VERSION"

  build-saturn:
    runs-on: ubuntu-latest
    needs: generate-version
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - id: log
        name: Log details
        run: |
          # VERSION
          BRANCH=${{needs.generate-version.outputs.output1}}
          echo "$BRANCH"
#          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
#          echo "Triggered on branch: $BRANCH"


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./projects/saturn/gradlew build -p ./projects/saturn/ -x test


  build-pluto:
    runs-on: ubuntu-latest
    needs: build-saturn
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log details
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "Triggered on branch: $BRANCH"
          echo "${{needs.build-saturn.outputs.output1}}"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./projects/pluto/gradlew build -p ./projects/pluto/ -x test


  build-mercury:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Log details
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "Triggered on branch: $BRANCH"

      - name: Install FE dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install`
          dir: ./projects/mercury/

      - name: Build FE bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build`
          dir: ./projects/mercury/

      - name: Run FE tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test`
          dir: ./projects/mercury/