dependencies:
- name: jupyterhub
  version: "0.7"
  repository: https://jupyterhub.github.io/helm-chart/
- name: pluto
  version: v0.2.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: mercury
  version: v0.2.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: titan
  version: v0.2.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: ceres
  version: v0.2.x
  repository: https://chartmuseum.jx.test.fairdev.app/
- name: neptune
  version: v0.4.x
  repository: https://chartmuseum.jx.test.fairdev.app/


