# Default values for vre.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Set specific workspace name. Defaults to release name
# Please note that if this is set, also set it for pluto in `pluto.workspace.name`
nameOverride:

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Hyperspace that this workspace is connected to
# Please note that pluto also has to know about the
# keycloak baseUrl and realm, see the pluto configuration
hyperspace:
    tls: true
    domain:
    locationOverrides:
        keycloak:

    # TODO: determine better way to handle keycloak credentials
    # Keycloak credentials are needed to setup the workspace (e.g. users, clients)
    # in keycloak. Please note that this is not a sustainable way of doing, due
    # to the sensitive nature of these parameters
    #
    # We could either:
    # - have the hyperspace setup keycloak itself, when creating a new workspace
    # - use temporary credentials for setting up these users
    # - ...
    keycloak:
        username:
        password:
        realm:
        clientSecret:


# Setup ingress for workspace components
workspace:
    ingress:
        enabled: true
        domain:
        annotations:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: clouddns

    testuser:
         password: fairspace123

    # Scripts for setting up keycloak for a workspace
    configurationScripts:
        dockerRepository: docker-registry.jx.test.fairdev.app
        image: fairspace/keycloak-configuration
        configurationScriptsTag: 0.0.20
        pullPolicy: IfNotPresent

# Specific settings for pluto
# Default configuration points to titan, mercury and neptune
# in the same workspace
pluto:
  overrides:
    keycloak:
      client:
        secretNamePostfix: oauth-client

  keycloak:
    baseUrl:
    realm:
    redirectAfterLogoutUrl: https://fairspace.com

# Specific settings for JupyterHub subchart
jupyterhub:
    singleuser:
      image:
        name: "jupyter/datascience-notebook"
        tag: "137a295ff71b"
      defaultUrl: "/lab"
    hub:
        ingress:
            enabled: false
        extraConfig: |
            c.KubeSpawner.cmd = ['jupyter-labhub']
        extraEnv:
            OAUTH2_AUTHORIZE_URL: https://${host}/auth/realms/${realm}/protocol/openid-connect/auth
            OAUTH2_TOKEN_URL: https://${host}/auth/realms/${realm}/protocol/openid-connect/token
        auth:
            type: custom
            custom:
                className: oauthenticator.generic.GenericOAuthenticator
                config:
                    client_id: "y0urc1logonc1ient1d"
                    client_secret: "an0ther1ongs3cretstr1ng"
                    token_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/token
                    userdata_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/userinfo
                    userdata_method: GET
                    userdata_params: {'state': 'state'}
                    username_key: preferred_username
    proxy:
        secretToken: "7a437e0359eca81661e82836965bf2b5dc07db4ff10b7686cb18762e601799d9"

# Specific settings for Ceres subchart
ceres:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 512Mi
      subPath: "ceres-db"
      mountPath: /data/ceres
    app:
      oauth2:
        baseUrl:
        realm:

# Specific settings for Neptune subchart
neptune:
    app:
      oauth2:
        baseUrl: 
        realm:
      metadata:
        baseUrl:

# Specific settings for Titan subchart                
titan:
    auth:
      jwksUrl:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 512Mi
      subPath: "titan"
      mountPath: /data

